image: Visual Studio 2017

init:
- git config --global core.autocrlf input

clone_folder: c:\projects\ht
shallow_clone: true

matrix:
  fast_finish: false

platform:
- x64

configuration:
- Debug

environment:
  matrix:
  - TOOLCHAIN: msvc15

install:
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
- mkdir build
- cd build
- cmake .. %CMAKE_CONFIGURE_FLAGS%
- cmake --build . %CMAKE_BUILD_FLAGS%